# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImage的使用' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GPUImage', '~> 0.1.7'
end
